model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_in_channels: 1

    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: true
    train:
      target: ldm.data.dcm_CTA.CTAHeartFULLIMAGE
      params:
        data_root: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/GE_train
        yaml_path: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/yaml/GE_train.yaml
        construct_method: strictly_balance
        load_modality_list: [ 'contrast', 'non_contrast' ]
        size: 256
        flip_p: 0.5
        debug: False
    validation:
      target: ldm.data.dcm_CTA.CTAHeartFULLIMAGE
      params:
        data_root: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/GE_val
        yaml_path: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/yaml/GE_val.yaml
        construct_method: strictly_balance
        load_modality_list: [ 'contrast', 'non_contrast' ]
        size: 256
        flip_p: 0
        debug: False

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
