model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: contrast
    cond_stage_key: non_contrast
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 640

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: /mnt/disk10T/home/wengtaohan/Code/latent-diffusion-main/logs/2024-02-17T12-19-35_autoencoder_kl_64x64x3/checkpoints/last.ckpt
        monitor: "val/rec_loss"
        embed_dim: 3
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 0.000001
            disc_weight: 0.5
            disc_in_channels: 1

        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0

    cond_stage_config: __is_first_stage__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: true
    train:
      target: ldm.data.dcm_CTA.CTAHeart
      params:
        data_root: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/GE_train
        yaml_path: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/yaml/GE_train.yaml
        construct_method: strictly_balance
        load_modality_list: [ 'contrast', 'non_contrast' ]
        size: 256
        flip_p: 0.5
        debug: False
    validation:
      target: ldm.data.dcm_CTA.CTAHeartFULLIMAGE
      params:
        data_root: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/GE_val
        yaml_path: /mnt/disk10T/home/wengtaohan/database/CTA/dcm_img/dataset/yaml/GE_val.yaml
        construct_method: strictly_balance
        load_modality_list: [ 'contrast', 'non_contrast' ]
        size: 256
        flip_p: 0
        debug: False


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True